pip install akinator.py
pip install apscheduler
pip install aiohttp
pip install aiofiles
pip install bs4
pip install cairosvg
pip install cfscrape
pip install enhancer==0.3.4
pip install gingerit
pip install google-api-python-client==2.31.0
pip install html-telegraph-poster==0.4.0
pip install htmlwebshot==0.1.2
pip install lottie==0.6.9
pip install multiprocess==0.70.12.2
pip install pyproject.toml
pip install lxml
#pip install numpy==1.21.2
pip install oauth2client==4.1.3
pip install pillow>=7.0.0
pip install image
pip install profanitydetector
pip install psutil==5.8.0
pip install pygments
pip install pymongo[srv]
pip install pypdf2==1.26.0
pip install pytz==2021.1
pip install pyyaml==5.4.1
pip install qrcode==7.3
pip install requests==2.26.0
pip install tabulate==0.8.9
pip install telegraph
pip install tgcrypto
pip install youtube-search-python==1.6.1
pip install yt-dlp
pip install pygments
pip install wheel
pip install redis
pip install jsonschema
pip install setuptools
pip install wrapt
pip install https://github.com/New-dev0/Telethon/archive/Artifact.zip
pip install pyUltroid
#pip install pyultroid
pip install python-Levenshtein
pip install fuzzywuzzy
#pip install numpy